#!/usr/bin/env python

""" MultiQC submodule to parse output from edgeR MDS plot data
generated by the NGI-RNAseq best practice analysis pipeline
https://github.com/SciLifeLab/NGI-RNAseq/ """

from collections import OrderedDict
import logging
import re

from multiqc import config, plots


# Initialise the logger
log = logging.getLogger('multiqc.modules.ngi_rnaseq')


def parse_reports(self):
    """ Find bamtools stats reports and parse their data """
    
    # Set up vars
    self.mds_plot_data = dict()
    
    # Default search pattern
    try:
        sp = config.sp['ngi_rnaseq']['mds_plot']
    except KeyError:
        sp = {'fn': 'edgeR_MDS_plot_coordinates.txt'}
    
    # Go through files and parse data using regexes
    found_mds_plot = False
    data = {}
    xTitle = None
    yTitle = None
    for f in self.find_log_files(sp):
        # Parse the file
        for l in f['f'].splitlines():
            s = l.split()
            if xTitle is None:
                xTitle = s[0]
                yTitle = s[1]
            else:
                data[s[0]] = [{'x': float(s[1]), 'y': float(s[2])}]
        # Should only have one MDS plot per report
        if found_mds_plot:
            log.debug("Duplicate sample name found! Overwriting: {}".format(f['s_name']))
        found_mds_plot = True
        self.add_data_source(f, section='mds_plot')
    
    if found_mds_plot:
        pconfig = {
            'xTitle': xTitle,
            'yTitle': yTitle
        }
        self.sections.append({
            'name': 'MDS Plot',
            'anchor': 'ngi_rnaseq-mds_plot',
            'content': plots.scatter.plot(data, pconfig)
        })
    
    # Return number of samples found
    return 1 if found_mds_plot else 0
    